site_name: Twitter Requirements

nav:
    - Home: index.md
    - PÅ•e-rastreabilidade:
      - RichPicture: richpicture.md

site_url: null
repo_url: https://github.com/Requisitos2-2019/Twitter

theme: yeti
